theme: null

collections:
  geospatial:
    output: true
    permalink: /global-education-observatory/geospatial/:name/
  personnel:
    output: true
    permalink: /global-education-observatory/personnel/:name/
  resources:
    output: true
    permalink: /global-education-observatory/resources/:name/
  outcomes:
    output: true
    permalink: /global-education-observatory/outcomes/:name/

defaults:
  - scope:
      path: ""
      type: geospatial
    values:
      layout: dataset
      theme: geospatial

  - scope:
      path: ""
      type: personnel
    values:
      layout: dataset
      theme: personnel
