theme: null

collections:
  geospatial:
    output: true
    permalink: /geospatial/:name/
  personnel:
    output: true
    permalink: /personnel/:name/
  resources:
    output: true
    permalink: /resources/:name/
  outcomes:
    output: true
    permalink: /outcomes/:name/

defaults:
  - scope:
      path: ""
      type: geospatial
    values:
      layout: dataset
      theme: geospatial

  - scope:
      path: ""
      type: personnel
    values:
      layout: dataset
      theme: personnel
